name: Build

on: [push, pull_request]

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build sdist
        run: |
          pipx run build --sdist --outdir ./wheelhouse ./python-package

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: ./wheelhouse/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build_sdist
    strategy:
      matrix:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-15-intel, macos-14]

    steps:
      - name: Download sdist
        uses: actions/download-artifact@v5
        with:
          name: cibw-sdist
          path: ./wheelhouse

      - name: Get filename for sdist
        id: sdist-path
        shell: bash
        run: |
            SDIST_PATH=$(ls -A1 ./wheelhouse/*.tar.gz)
            echo "path=${SDIST_PATH}" >> "${GITHUB_OUTPUT}"

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        with:
          package-dir: "${{ steps.sdist-path.outputs.path }}"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
